# Last modified: 2023 Nov 26
image: ghcr.io/rocker-org/devcontainer/geospatial:4

# These scripts are executed each time the container starts.
# 1. Ensures that `$HOME/.bashrc.d` files are sourced.
# 2. Sets up the `bashrc_d` configuration.
# 3. Adds the `config-r.sh` file to be sourced if it's not already present.
# 4. Sources the `config-r.sh` file.
# 5. Sources the `config-r-vscode.sh` file if the environment is GitPod.
# 6. Adds the `config-r-vscode.sh` file to be sourced if it's not already present in the case of CodeSpaces.
# 7. Sources the `config-r-vscode.sh` file in the case of CodeSpaces.
# 8. Clones all repositories in repos-to-clone.list.
# 9. Adds all repositories in repos-to-clone.list to the workspace file (EntireProject.code-workspace).

tasks:
  - name: Config R and VS Code workspace
    command: |
      chmod 755 .devcontainer/scripts/*sh
      .devcontainer/scripts/post-start-command.sh 

vscode:
  extensions:
    - quarto.quarto
    - REditorSupport.r
    - bierner.markdown-preview-github-styles
    - eamodio.gitlens
    - mathematic.vscode-pdf
