library(testthat)
devtools::load_all()
.test_set_select()
devtools::test_active_file("tests/testthat/test-build.R")

library(testthat)
# devtools::load_all(path = file.path(Sys.getenv("pkg"), "projr"))
devtools::load_all()
.test_unset_select()
.test_set_fast()
devtools::test()

library(testthat)
devtools::load_all()
devtools::test_active_file("tests/testthat/test-yml.R")
Sys.getenv("GITHUB_PAT")

library(testthat)
devtools::load_all()
.projr_test_coverage()
