projr_init <- function(git = TRUE,
                       git_commit = TRUE,
                       github = TRUE,
                       github_public = FALSE,
                       github_org = NULL,
                       # whether to initialise projr-specified directories
                       dir = TRUE,
                       readme = TRUE,
                       readme_rmd = FALSE,
                       renv = FALSE,
                       desc = FALSE,
                       license = NULL,
                       citation = FALSE,
                       projr_yml = FALSE,
                       lit_doc = NULL) {

  #

  # initialise Git
  .projr_init_std_git(git, git_commit)

}

# ========================================
# README
# ========================================

.projr_init_readme_

.projr_init_readme <- function(init_readme) {
  if (!init_readme) {
    return(invisible(FALSE))
  }
  readme_contents <- c(
    "# README",
    "",
    "The purpose of this project is to",
    "`[briefly describe the project's goals and objectives]`",
    "",
    "## Reproducing the analysis",
    "",
    "Run the following code from the project working directory:",
    "",
    "```r",
    "if (!requireNamespace(\"projrsimple\", quietly = TRUE)) {",
    "  if (!requireNamespace(\"remotes\", quietly = TRUE)) {",
    "    install.packages(\"remotes\")",
    "  }",
    "  remotes::install_github(\"MiguelRodo/projrsimple\")",
    "}",
    "projrsimple::projr_run()",
    "```",
    "",
    "<!--",
    "Change the above instructions, e.g. specify non-default parameters or",
    "another approach entirely",
    "-->",
    "",
    "## Directory Structure",
    "",
    "This project follows a structured directory layout to organise input",
    "materials, generated outputs, and temporary files efficiently.",
    "",
    "- **`_reference/**: Static documents that are not generated by analyses,",
    "  such as assignment questions and reference materials.",
    "- **`_raw_data/**: Raw, unprocessed data files.",
    "- **`docs/**: Rendered documents produced from R Markdown (`Rmd`) or",
    "  Quarto (`qmd`) scripts.",
    "- **`_output/**: Final analysis results, processed data, and exported",
    "  reports.",
    "- **`_tmp/**: Temporary storage for cached outputs, intermediate",
    "  results, and shared files.",
    "",
    "## Links",
    "",
    "- `[URLs to data sources (e.g. OneDrive), GitHub repos, etc.]`",
    "",
    "## Details",
    "",
    "`[Methods, timeline, team, data sources, software/tools, etc.]`"
  )
  writeLines(readme_contents, con = "README.md")
  message("Created README.md.")
  invisible(TRUE)
}

# ========================================
# Git
# ========================================

.projr_init_std_git <- function(git, commit) {
  if (!git) {
    return(invisible(FALSE))
  }
  .projr_git_system_setup()
  .projr_git_init()
  projr_ignore_auto()
  if (commit) {
    .projr_init_git_commit()
  }
  .projr_init_git_suggest_git()
  invisible(TRUE)
}
