# cite
# -----------------

#' @rdname yml-cite
#' @title Set citation options
#' @export
#'
#' @description
#'
#' .yml_cite_set` sets the citation options in `_projr.yml`.
#'
#' The options are:
#' \describe{
#'  \item{codemeta}{whether to generate a codemeta.json file.}
#' \item{cff}{
#' whether to generate a CITATION.cff file.
#' Indexable by GitHub and Zenodo.
#' }
#' \item{inst-citation}{
#' whether to generate a CITATION file in the inst/ directory.
#' If the project is installed as an `R` package,
#' then citation data can be generated by
#' `citation(package = <project_name>)`.
#' }
#' }
#' The default is to leave all the settings unchanged.
#'
#' If these settings are not setting in `_projr.yml`,
#' then the default is to generate a codemeta.json file,
#' a CITATION.cff file and a CITATION file in the inst/ directory.
#'
#' .yml_cite_set_default` sets all citation options to default (`TRUE`).
#'
#' @param all logical.
#' Whether to set all the options
#' to `TRUE` or `FALSE`.
#' If `NULL`, then `codemeta`, `cff` and `inst_citation` are used.
#' Default is `NULL`.
#' @param codemeta logical.
#' Whether to generate a codemeta.json file.
#' If `NULL`, then setting is not changed.
#' @param cff logical.
#' Whether to generate a CITATION.cff file.
#' If `NULL`, then setting is not changed.
#' @param inst_citation logical.
#' Whether to generate a CITATION file in the inst/ directory.
#' If `NULL`, then setting is not changed.
#' @param simplify_identical logical.
#' If `TRUE`, then if all the settings are the same
#' then only `cite: TRUE` or `cite: FALSE` is written to `_projr.yml`.
#' Default is `TRUE`.
#' @param simplify_default logical.
#' If `TRUE`, then if all the settings are the same
#' and equl to the default (`TRUE`),
#' then the settings are not recorded in the `projr`
#' configuration file (as the default will be equal to it).
#' @param profile character.
#' The profile to write to.
#' Default is "default", in which case it writes to `_projr.yml`.
#'
#' @examples
#' \dontrun{
#' # set all to TRUE
#' projr_yml_cite_set(all = TRUE)
#'
#' # set all to FALSE
#' projr_yml_cite_set(all = FALSE)
#'
#' # set only cff to FALSE
#' projr_yml_cite_set(cff = FALSE)
#'
#' # revert to defaults
#' projr_yml_cite_set()
#' }
#'
projr_yml_cite_set <- function(all = NULL,
                               codemeta = NULL,
                               cff = NULL,
                               inst_citation = NULL,
                               simplify_identical = TRUE,
                               simplify_default = TRUE,
                               profile = "default") {
  .yml_cite_set_check(
    all = all, codemeta = codemeta, cff = cff,
    inst_citation = inst_citation, profile = profile,
    simplify_identical = simplify_identical,
    simplify_default = simplify_default
  )

  if (!is.null(all)) {
    codemeta <- all
    cff <- all
    inst_citation <- all
  }

  .yml_cite_set_ind(
    codemeta = codemeta, cff = cff, inst_citation = inst_citation,
    profile = profile, simplify_default = simplify_default
  )

  .yml_cite_simplify(simplify_identical, simplify_default, profile)
}

.yml_cite_set_check <- function(all,
                                codemeta,
                                cff,
                                inst_citation,
                                profile,
                                simplify_identical,
                                simplify_default) {
  if (!is.null(all)) {
    .assert_flag(all)
  } else {
    .assert_flag(codemeta)
    .assert_flag(cff)
    .assert_flag(inst_citation)
  }
  .assert_flag(simplify_identical, TRUE)
  .assert_flag(simplify_default, TRUE)
  .assert_string(profile)
}

.yml_cite_set_ind <- function(codemeta,
                              cff,
                              inst_citation,
                              profile,
                              simplify_default) {
  if (!is.null(codemeta)) {
    .yml_cite_set_codemeta(codemeta, simplify_default, profile)
  }
  if (!is.null(cff)) {
    .yml_cite_set_cff(cff, simplify_default, profile)
  }
  if (!is.null(inst_citation)) {
    .yml_cite_set_inst_citation(inst_citation, simplify_default, profile)
  }
}

#' @rdname yml-cite
#' @export
projr_yml_cite_set_default <- function(profile = "default",
                                       simplify_identical = TRUE,
                                       simplify_default = TRUE) {
  projr_yml_cite_set(
    all = TRUE, profile = profile,
    simplify_identical = simplify_identical,
    simplify_default = simplify_default
  )
}

.yml_cite_set_codemeta <- function(codemeta,
                                   simplify_default,
                                   profile) {
  codemeta_pre <- .yml_cite_get_codemeta(profile = profile)
  if (all(c(codemeta_pre, codemeta)) && simplify_default) {
    return(invisible(FALSE))
  }
  .yml_cite_set_mix(list("codemeta" = codemeta), profile)
  invisible(TRUE)
}

.yml_cite_get_codemeta <- function(profile) {
  .yml_cite_get_opt("codemeta", profile)
}

.yml_cite_set_mix <- function(cite_list_single, profile) {
  .yml_cite_get_combn_with_written(
    cite_list_single, profile
  ) |>
    .yml_cite_get_ordered() |>
    .yml_cite_set(profile)
}

.yml_cite_get_combn_with_written <- function(cite_list_single,
                                             profile) {
  yml_cite <- .yml_cite_get(profile)
  cite_list_single |> append(
    yml_cite[setdiff(names(yml_cite), names(cite_list_single))]
  )
}

.yml_cite_get_ordered <- function(yml_cite) {
  nm_vec_actual <- names(yml_cite)
  nm_vec_possible <- c("codemeta", "cff", "inst-citation")
  nm_vec_ordered <- nm_vec_possible[nm_vec_possible %in% nm_vec_actual]
  yml_cite[nm_vec_ordered]
}

.yml_cite_set_cff <- function(cff,
                              simplify_default,
                              profile) {
  cff_pre <- .yml_cite_get_cff(profile = profile)
  if (all(c(cff_pre, cff)) && simplify_default) {
    return(invisible(FALSE))
  }
  .yml_cite_set_mix(list("cff" = cff), profile)
  invisible(TRUE)
}

.yml_cite_get_cff <- function(profile) {
  .yml_cite_get_opt("cff", profile)
}

.yml_cite_get_opt <- function(opt, profile) {
  yml_cite <- .yml_cite_get(profile)
  if (is.null(yml_cite) || isTRUE(yml_cite)) {
    return(TRUE)
  }
  if (isFALSE(yml_cite)) {
    return(FALSE)
  }
  if (is.null(yml_cite[[opt]])) {
    return(TRUE)
  }
  yml_cite[[opt]]
}

.yml_cite_set_inst_citation <- function(inst_citation,
                                        simplify_default,
                                        profile) {
  inst_citation_pre <- .yml_cite_get_inst_citation(profile = profile)
  if (all(c(inst_citation_pre, inst_citation)) && simplify_default) {
    return(invisible(FALSE))
  }
  .yml_cite_set_mix(list("inst-citation" = inst_citation), profile)
  invisible(TRUE)
}

.yml_cite_get_inst_citation <- function(profile) {
  .yml_cite_get_opt("inst-citation", profile)
}

.yml_cite_get <- function(profile) {
  init_list <- .yml_get(profile)[["build"]][["cite"]]
  if (length(init_list) == 0L) {
    return(NULL)
  }
  init_list
}

.yml_cite_set <- function(yml_cite, profile = NULL) {
  .yml_build_set_nm(yml_cite, "cite", profile)
}

.yml_cite_simplify <- function(simplify_identical,
                               simplify_default,
                               profile) {
  .yml_cite_simplify_identical(simplify_identical, profile)
  .yml_cite_simplify_default(simplify_default, profile)
}

.yml_cite_simplify_identical <- function(simplify_identical,
                                         profile) {
  if (!simplify_identical) {
    return(invisible(FALSE))
  }

  codemeta <- .yml_cite_get_codemeta(profile)
  cff <- .yml_cite_get_cff(profile)
  inst_citation <- .yml_cite_get_inst_citation(profile)
  if (all(c(codemeta, cff, inst_citation))) {
    .yml_cite_set(TRUE, profile)
  } else if (!any(c(codemeta, cff, inst_citation))) {
    .yml_cite_set(FALSE, profile)
  }

  invisible(TRUE)
}

.yml_cite_simplify_default <- function(simplify_default,
                                       profile) {
  if (!simplify_default) {
    return(invisible(FALSE))
  }

  codemeta <- .yml_cite_get_codemeta(profile)
  cff <- .yml_cite_get_cff(profile)
  inst_citation <- .yml_cite_get_inst_citation(profile)
  if (all(c(codemeta, cff, inst_citation))) {
    .yml_cite_set(NULL, profile)
  }

  invisible(TRUE)
}
