name: 'Pre-build Dev Container'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use cache when building the image'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Dev Container
        uses: SATVILab/actions/build-devcontainer@v1.2.5
        with:
          use_cache: ${{ github.event.inputs.use_cache }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
